---
abstract: 'Configuration data with context'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Context
provides:
  Data::Context:
    file: lib/Data/Context.pm
    version: v0.1.0
  Data::Context::Actions:
    file: lib/Data/Context/Actions.pm
    version: v0.1.0
  Data::Context::Finder:
    file: lib/Data/Context/Finder.pm
    version: v0.1.0
  Data::Context::Finder::File:
    file: lib/Data/Context/Finder/File.pm
    version: v0.1.0
  Data::Context::Instance:
    file: lib/Data/Context/Instance.pm
    version: v0.1.0
  Data::Context::Loader:
    file: lib/Data/Context/Loader.pm
    version: v0.1.0
  Data::Context::Loader::File:
    file: lib/Data/Context/Loader/File.pm
    version: v0.1.0
  Data::Context::Loader::File::JS:
    file: lib/Data/Context/Loader/File/JS.pm
    version: v0.0.1
  Data::Context::Loader::File::JSON:
    file: lib/Data/Context/Loader/File/JSON.pm
    version: v0.0.1
  Data::Context::Loader::File::XML:
    file: lib/Data/Context/Loader/File/XML.pm
    version: v0.0.1
  Data::Context::Loader::File::YAML:
    file: lib/Data/Context/Loader/File/YAML.pm
    version: v0.0.1
  Data::Context::Log:
    file: lib/Data/Context/Log.pm
  Data::Context::Util:
    file: lib/Data/Context/Util.pm
    version: v0.1.0
recommends:
  JSON: 0
  Pod::Coverage: 0
  Test::Kwalitee: 0
  Test::Perl::Critic: 0
  Test::Spelling: 0
  XML::Simple: 0
  YAML::XS: 0
requires:
  Class::Inspector: 0
  Clone: 0
  Hash::Merge: 0
  IO::String: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Path::Class: 0
  namespace::autoclean: 0
  perl: 5.008
  version: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data::Context
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/Data-Context.git
version: v0.1.0
